export const data = [
    {
        name: "name1",
        quantity: 1,
        food: "food1",
        select: "select1",
        option: true,
        ref: "ref1",
    },
    {
        name: "name2",
        quantity: 2,
        food: "food2",
        select: "select2",
        option: true,
        ref: "ref2",
    },
    {
        name: "name3",
        quantity: 3,
        food: "food3",
        select: "select3",
        option: false,
        ref: "ref3",
    },
    {
        name: "name4",
        quantity: 4,
        food: "food4",
        select: "select4",
        option: false,
        ref: "ref4",
    },
    {
        name: "name5",
        quantity: 5,
        food: "food5",
        select: "select5",
        option: true,
        ref: "ref5",
    },
];

const ingredients = [
    "사과",
    "바나나",
    "당근",
    "다시마",
    "계란",
    "감자",
    "토마토",
    "양파",
    "호박",
    "오이",
];
